groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.math.BigDecimal#minus. Cannot resolve which method to invoke for [null] due to overlapping prototypes between: [class java.lang.Character]